name = "frameit"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "frameit-events"
database_id = "82d3da46-b885-451c-ae1e-855bcbf28dca"

[vars]
ENVIRONMENT = "production"
